### ISSUE TITLE
NPM v3.x: "Cannot rename missing "jade" task."

### ISSUE THREAD

**Issue by valeriansaliou** [AdesisNetlife/grunt-pug-i18n#26]
Hello,

Thanks for the great work first :)

After upgrading my stack to NPM v3.3.x (this is probably a general issue of NPM v3.x branch), grunt-jade-i18n stopped compiling my files because of:

```bash
>> Tasks directory "/Users/valerian/Documents/Web/xxxxxx/node_modules/grunt-jade-i18n/node_modules/grunt-contrib-jade/tasks" not found.
>> Cannot rename missing "jade" task.
```

I was first thinking it could be due to the fact I was still using NodeJS v0.10.x, paired w/ the latest NPM version. I upgraded to NodeJS v4.x, and things didn't get better.

Looks like this is the only Grunt contrib plugin that fails on this recent build stack, others (on the many) I'm using are still passing.

**Comment by skezo** [comment]
@valeriansaliou 
Did you manage to resolve this? I am seeing the same issue when deploying to an Azure website.

**Comment by skezo** [comment]
I think my issue is similar to the one outlined here https://github.com/AdesisNetlife/grunt-jade-i18n/issues/16 basically Azure is bringing most sub modules to the root of the node modules folder.

**Comment by h2non** [comment]
This should be fixed now.
