### ISSUE TITLE
Rename to grunt-pug-i18n?

### ISSUE THREAD

**Issue by Lowgain** [AdesisNetlife/grunt-pug-i18n#33]
It appears Jade has been renamed to pug (re: https://github.com/pugjs/pug/issues/2184) as well as grunt-jade-i18n (now https://github.com/gruntjs/grunt-contrib-pug). Makes sense to keep up-to-date I'd think!

**Comment by h2non** [comment]
Done and released in [npm](https://www.npmjs.com/package/grunt-pug-i18n).
